# general settings
name: debug
# name: 006_baseline_BasicVSR_x4_f64b30_CED_300k_B8G2_wandb
# name: debug_test_BasicVSR_CED
model_type: VideoRecurrentModel
scale: 4
num_gpu: auto  # official: 8 GPUs
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: CED
    type: CEDOnlyFramesDataset
    # dataroot_gt: datasets/CED/train_sharp
    # dataroot_lq: datasets/CED/train_sharp_bicubic_x2
    # (for lmdb)
    dataroot_gt: datasets/CED_h5/Voxel_3/HR
    dataroot_lq: datasets/CED_h5/Voxel_3/LRx4
    meta_info_file: basicsr/data/meta_info/meta_info_CED_3_h5_train.txt
    # io_backend:
      # type: disk
    # test_mode: False
    io_backend:
      type: hdf5

    num_frame: 15
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 0
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 200
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: CED11
    type: CEDOnlyFramesTestDataset
    dataroot_gt: datasets/CED_3_h5/Voxel_3/HR
    dataroot_lq: datasets/CED_3_h5/Voxel_3/LRx4
    meta_info_file: basicsr/data/meta_info/meta_info_CED_3_h5_test.txt
    scale: 4

    # cache_data: true # not needed
    io_backend:
      type: hdf5

    # num_frame: -1  # not needed

# network structures
network_g:
  type: BasicVSR
  num_feat: 64
  num_block: 30
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: e2vsr
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
