# general settings
name: debug
# name: BasicVSR_vimeo90k_BIx4
# name: 015_e2vsr_x2_vimeo_300k_f64b30_B8G2_wandb
# name: debug_test_BasicVSR_CED
model_type: E2VSRModel
scale: 2
num_gpu: auto  # official: 8 GPUs
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: Vimeo90kWithEventsDataset
    # dataroot_gt: datasets/CED/train_sharp
    # dataroot_lq: datasets/CED/train_sharp_bicubic_x2
    # (for lmdb)
    dataroot_gt: datasets/vimeo_septuplet_h5/Voxel_3/HR
    dataroot_lq: datasets/vimeo_septuplet_h5/Voxel_3/LRx2
    meta_info_file: basicsr/data/meta_info/debug_loss_nan.txt
    is_event: true
    # io_backend:
      # type: disk
    # test_mode: False
    io_backend:
      type: hdf5

    num_frame: -1
    gt_size: 128
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    flip_sequences: true

    # data loader
    num_worker_per_gpu: 0
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: Vid4
    type: Vid4WithEventsTestDataset
    dataroot_gt: datasets/Vid4_h5/Voxel_3/HR
    dataroot_lq: datasets/Vid4_h5/Voxel_3/LRx2
    meta_info_file: basicsr/data/meta_info/meta_info_Vid4_h5.txt
    is_event: true
    scale: 2

    # cache_data: true # not needed
    io_backend:
      type: hdf5

    # num_frame: -1  # not needed

# network structures
network_g:
  type: E2VSR_x2
  num_feat: 64
  num_block: 30
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: e2vsr
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
